# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\criss\OneDrive - Universidad de Guadalajara\uni9 docs\SEM IA 2\AntiSpamAI\Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(246, 54)
        self.pushButton_Load = QtWidgets.QPushButton(dialog)
        self.pushButton_Load.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.pushButton_Load.setObjectName("pushButton_Load")
        self.label_Label = QtWidgets.QLabel(dialog)
        self.label_Label.setGeometry(QtCore.QRect(110, 10, 91, 16))
        self.label_Label.setObjectName("label_Label")
        self.label_Error = QtWidgets.QLabel(dialog)
        self.label_Error.setGeometry(QtCore.QRect(70, 30, 91, 16))
        self.label_Error.setText("")
        self.label_Error.setObjectName("label_Error")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Practica Final"))
        self.pushButton_Load.setText(_translate("dialog", "Carga correo"))
        self.label_Label.setText(_translate("dialog", " "))
