# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\criss\OneDrive - Universidad de Guadalajara\uni9 docs\SEM IA 2\AntiSpamAI\Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(595, 330)
        self.frame = QtWidgets.QFrame(dialog)
        self.frame.setGeometry(QtCore.QRect(9, 9, 371, 311))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 371, 311))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_Load = QtWidgets.QPushButton(dialog)
        self.pushButton_Load.setGeometry(QtCore.QRect(390, 20, 75, 23))
        self.pushButton_Load.setObjectName("pushButton_Load")
        self.pushButton_Plot = QtWidgets.QPushButton(dialog)
        self.pushButton_Plot.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.pushButton_Plot.setObjectName("pushButton_Plot")
        self.doubleSpinBox_LR = QtWidgets.QDoubleSpinBox(dialog)
        self.doubleSpinBox_LR.setGeometry(QtCore.QRect(520, 130, 62, 22))
        self.doubleSpinBox_LR.setMinimum(-99.99)
        self.doubleSpinBox_LR.setObjectName("doubleSpinBox_LR")
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setGeometry(QtCore.QRect(490, 130, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(dialog)
        self.label_5.setGeometry(QtCore.QRect(390, 130, 47, 13))
        self.label_5.setObjectName("label_5")
        self.spinBox_Epochs = QtWidgets.QSpinBox(dialog)
        self.spinBox_Epochs.setEnabled(True)
        self.spinBox_Epochs.setGeometry(QtCore.QRect(430, 130, 51, 22))
        self.spinBox_Epochs.setFrame(True)
        self.spinBox_Epochs.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_Epochs.setKeyboardTracking(True)
        self.spinBox_Epochs.setObjectName("spinBox_Epochs")
        self.pushButton_Train = QtWidgets.QPushButton(dialog)
        self.pushButton_Train.setGeometry(QtCore.QRect(390, 80, 75, 23))
        self.pushButton_Train.setObjectName("pushButton_Train")
        self.label_Presicion = QtWidgets.QLabel(dialog)
        self.label_Presicion.setGeometry(QtCore.QRect(400, 220, 91, 16))
        self.label_Presicion.setObjectName("label_Presicion")
        self.label_F1 = QtWidgets.QLabel(dialog)
        self.label_F1.setGeometry(QtCore.QRect(500, 220, 91, 16))
        self.label_F1.setObjectName("label_F1")
        self.label_MC = QtWidgets.QLabel(dialog)
        self.label_MC.setGeometry(QtCore.QRect(430, 240, 111, 51))
        self.label_MC.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_MC.setObjectName("label_MC")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Practica 4"))
        self.pushButton_Load.setText(_translate("dialog", "Carga datos"))
        self.pushButton_Plot.setText(_translate("dialog", "Grafica"))
        self.label_4.setText(_translate("dialog", "<html><head/><body><p>ɳ=</p></body></html>"))
        self.label_5.setText(_translate("dialog", "<html><head/><body><p>Eta=</p></body></html>"))
        self.pushButton_Train.setText(_translate("dialog", "Entrenar"))
        self.label_Presicion.setText(_translate("dialog", "Presicion:"))
        self.label_F1.setText(_translate("dialog", "F1 Score:"))
        self.label_MC.setText(_translate("dialog", "Matriz de confusion:"))
